export enum TargetLanguage {
  ChineseTW = '繁體中文',
  English = 'English',
  Korean = '한국어',
  French = 'Français',
  Spanish = 'Español',
  Thai = 'ไทย',
  Filipino = 'Tagalog',
  Vietnamese = 'Tiếng Việt'
}

export interface MenuItem {
  id: string; // Unique ID generated by frontend
  originalName: string;
  translatedName: string;
  price: number;
  category?: string;
  explanation?: string; // Deep explanation (lazy loaded)
  shortDescription?: string; // Brief description from initial parse
  allergy_warning?: boolean;
  dietary_tags?: string[];
}

export interface MenuData {
  items: MenuItem[];
  originalCurrency: string;
  targetCurrency: string;
  exchangeRate: number; // 1 Original = X Target
  detectedLanguage: string;
}

export interface CartItem {
  item: MenuItem;
  quantity: number;
}

export type Cart = Record<string, CartItem>; // Keyed by item.id

export interface HistoryRecord {
  id: string;
  timestamp: number;
  items: CartItem[];
  totalOriginalPrice: number;
  currency: string;
}

export type AppState = 'welcome' | 'processing' | 'ordering' | 'summary' | 'history';